name: "Complete Scout Analytics Deployment: Readiness + Flat Export + Validation"
steps:
  # Secure keychain-backed connection (no secrets in code)
  - include: bruno-keychain-conn.yml

  # Pre-deployment readiness checks
  - run: |
      set -e
      echo "🔍 Running pre-deployment readiness validation..."
      sqlcmd -S "$AZURE_SQL_CONN_STR" -i sql/validation/readiness_smoke_test.sql
      echo "✅ Readiness validation completed"
    shell: bash

  # Apply the single-key JOIN migration
  - write: sql/migrations/2025-09-25_v_flat_export_sheet_si_time.sql
    content: |
      /* v_flat_export_sheet — single-key joins on canonical_tx_id
         Time/Daypart/Weektype derived from SalesInteractions.TransactionDate (fallback to base) */
      CREATE OR ALTER VIEW dbo.v_flat_export_sheet AS
      WITH base AS (
        SELECT
          CAST(p.canonical_tx_id AS varchar(64))   AS Transaction_ID,
          CAST(p.total_amount AS decimal(18,2))    AS Transaction_Value,
          CAST(p.total_items  AS int)              AS Basket_Size,
          p.category                                AS Category,
          p.brand                                   AS Brand,
          p.txn_ts                                  AS base_txn_ts,
          p.daypart                                 AS base_daypart,
          p.weekday_weekend                         AS base_weektype,
          p.store_name                               AS Location
        FROM dbo.v_transactions_flat_production p
        -- Optional business toggle:
        -- WHERE p.is_completed = 1
      ),
      demo AS (
        /* Aggregate per transaction to one SI row */
        SELECT
          si.canonical_tx_id,
          MAX(si.TransactionDate)    AS si_txn_ts,
          MAX(CASE
            WHEN si.Age BETWEEN 18 AND 24 THEN '18-24'
            WHEN si.Age BETWEEN 25 AND 34 THEN '25-34'
            WHEN si.Age BETWEEN 35 AND 44 THEN '35-44'
            WHEN si.Age BETWEEN 45 AND 54 THEN '45-54'
            WHEN si.Age BETWEEN 55 AND 64 THEN '55-64'
            WHEN si.Age >= 65 THEN '65+'
            ELSE ''
          END) AS age_bracket,
          MAX(si.Gender)             AS gender,
          MAX(si.EmotionalState)     AS customer_type
        FROM dbo.SalesInteractions si
        WHERE si.canonical_tx_id IS NOT NULL
        GROUP BY si.canonical_tx_id
      ),
      personas AS (
        SELECT
          pr.canonical_tx_id,
          MAX(pr.role) AS inferred_role
        FROM ref.v_persona_inference pr
        WHERE pr.canonical_tx_id IS NOT NULL
        GROUP BY pr.canonical_tx_id
      ),
      subs AS (
        SELECT
          v.sessionId AS canonical_tx_id,
          MAX(CASE WHEN v.substitution_event = '1' THEN 1 ELSE 0 END) AS was_substitution
        FROM dbo.v_insight_base v
        WHERE v.sessionId IS NOT NULL
        GROUP BY v.sessionId
      )
      SELECT
        b.Transaction_ID,
        b.Transaction_Value,
        b.Basket_Size,
        b.Category,
        b.Brand,

        /* Daypart: prefer SI time */
        COALESCE(
          CASE
            WHEN d.si_txn_ts IS NULL THEN NULL
            WHEN DATEPART(HOUR, d.si_txn_ts) BETWEEN 5 AND 11 THEN 'Morning'
            WHEN DATEPART(HOUR, d.si_txn_ts) BETWEEN 12 AND 17 THEN 'Afternoon'
            WHEN DATEPART(HOUR, d.si_txn_ts) BETWEEN 18 AND 22 THEN 'Evening'
            ELSE 'Night'
          END,
          b.base_daypart
        ) AS Daypart,

        /* Demographics with persona inference: Age Gender Role */
        LTRIM(RTRIM(
          CONCAT(
            COALESCE(d.age_bracket,''),
            CASE WHEN COALESCE(d.gender,'') != '' THEN ' ' + d.gender ELSE '' END,
            CASE WHEN COALESCE(p.inferred_role,'') != '' AND COALESCE(p.inferred_role,'') != 'Regular'
                 THEN ' ' + p.inferred_role
                 WHEN COALESCE(d.customer_type,'') != '' THEN ' ' + d.customer_type
                 ELSE '' END
          )
        )) AS [Demographics (Age/Gender/Role)],

        /* Weekday/Weekend: prefer SI time */
        COALESCE(
          CASE WHEN d.si_txn_ts IS NULL THEN NULL
               WHEN DATENAME(WEEKDAY, d.si_txn_ts) IN ('Saturday','Sunday') THEN 'Weekend'
               ELSE 'Weekday'
          END,
          b.base_weektype
        ) AS Weekday_vs_Weekend,

        /* Time of transaction: prefer SI time */
        FORMAT(COALESCE(d.si_txn_ts, b.base_txn_ts), 'htt', 'en-US') AS [Time of transaction],

        b.Location,

        /* Co-purchases: by tx id; exclude primary brand/category */
        (
          SELECT STRING_AGG(
                   CASE
                     WHEN ti2.brand IS NOT NULL AND ti2.category IS NOT NULL THEN CONCAT(ti2.brand, ' (', ti2.category, ')')
                     WHEN ti2.brand IS NOT NULL THEN ti2.brand
                     WHEN ti2.category IS NOT NULL THEN ti2.category
                     ELSE ti2.product_name
                   END, ', '
                 )
          FROM dbo.TransactionItems ti2
          WHERE ti2.canonical_tx_id = b.Transaction_ID
            AND (
                  ti2.brand IS NULL
                  OR UPPER(LTRIM(RTRIM(ti2.brand))) <> UPPER(LTRIM(RTRIM(b.Brand)))
                )
            AND (
                  ti2.category IS NULL
                  OR UPPER(LTRIM(RTRIM(ti2.category))) <> UPPER(LTRIM(RTRIM(b.Category)))
                )
        ) AS Other_Products,

        CASE
          WHEN s.was_substitution = 1 THEN 'true'
          WHEN s.was_substitution = 0 THEN 'false'
          ELSE ''
        END AS Was_Substitution

      FROM base b
      LEFT JOIN demo d ON d.canonical_tx_id = b.Transaction_ID
      LEFT JOIN personas p ON p.canonical_tx_id = b.Transaction_ID
      LEFT JOIN subs s ON s.canonical_tx_id  = b.Transaction_ID;
      GO

      -- Permissions (adjust role if needed)
      IF EXISTS (SELECT 1 FROM sys.database_principals WHERE name = 'rpt_reader')
        GRANT SELECT ON dbo.v_flat_export_sheet TO rpt_reader;
      GO

  # Apply migration and run post-deployment validation
  - run: |
      set -e
      echo "🚀 Applying single-key JOIN migration..."
      sqlcmd -S "$AZURE_SQL_CONN_STR" -i sql/migrations/2025-09-25_v_flat_export_sheet_si_time.sql
      echo "✅ Migration applied successfully"

      echo "📊 Running post-deployment validation gates..."
      sqlcmd -S "$AZURE_SQL_CONN_STR" -i sql/validation/coverage_checks.sql -s "," -W -h -1 > out/coverage_checks.csv
      sqlcmd -S "$AZURE_SQL_CONN_STR" -i sql/validation/codebook_flat_export.sql -s "," -W -h -1 > out/codebook_flat_export.csv

      echo "✅ Validation gates completed"
    shell: bash

  # Extract final dataframe with validation
  - run: |
      set -e
      echo "💾 Extracting final flat dataframe..."
      python3 scripts/extract_flat_dataframe.py --out out/flat_dataframe.csv --limit 1000

      # Basic file validation
      if [[ -f "out/flat_dataframe.csv" ]]; then
        file_size=$(wc -c < out/flat_dataframe.csv)
        row_count=$(tail -n +2 out/flat_dataframe.csv | wc -l)
        echo "✅ Export successful:"
        echo "   File size: ${file_size} bytes"
        echo "   Row count: ${row_count} rows"

        # Validate CSV has exactly 12 columns
        header_cols=$(head -n 1 out/flat_dataframe.csv | tr ',' '\n' | wc -l)
        if [[ $header_cols -eq 12 ]]; then
          echo "   Columns: ✅ $header_cols (exact match)"
        else
          echo "   Columns: ❌ $header_cols (expected 12)"
          exit 1
        fi

        # Check for persona inference
        persona_count=$(grep -c "Student\|Worker\|Rider\|Parent\|Senior\|Reseller\|Teen\|Party\|Health\|Farmer" out/flat_dataframe.csv || echo "0")
        echo "   Persona inference: $persona_count rows with roles"

      else
        echo "❌ Export failed: file not created"
        exit 1
      fi
    shell: bash

  # Final smoke test on exported data
  - run: |
      set -e
      echo "🔥 Final smoke test on exported dataframe..."

      # Quick Python validation
      python3 -c "
import pandas as pd
import sys

try:
    df = pd.read_csv('out/flat_dataframe.csv')

    # Validate shape
    expected_cols = 12
    actual_cols = len(df.columns)
    if actual_cols != expected_cols:
        print(f'❌ Column count mismatch: {actual_cols} != {expected_cols}')
        sys.exit(1)

    # Validate required columns
    required = ['Transaction_ID', 'Transaction_Value', 'Category', 'Brand', 'Demographics (Age/Gender/Role)']
    missing = [col for col in required if col not in df.columns]
    if missing:
        print(f'❌ Missing columns: {missing}')
        sys.exit(1)

    # Check for duplicates
    duplicates = df['Transaction_ID'].duplicated().sum()
    if duplicates > 0:
        print(f'❌ Duplicate Transaction_IDs: {duplicates}')
        sys.exit(1)

    # Demographics format check
    demo_col = 'Demographics (Age/Gender/Role)'
    with_demographics = df[demo_col].notna().sum()
    persona_keywords = ['Student', 'Worker', 'Rider', 'Parent', 'Senior', 'Reseller', 'Teen', 'Party', 'Health', 'Farmer']
    with_personas = df[demo_col].str.contains('|'.join(persona_keywords), na=False).sum()

    print(f'✅ Validation successful:')
    print(f'   Rows: {len(df):,}')
    print(f'   Columns: {len(df.columns)} (exact match)')
    print(f'   Unique Transaction_IDs: {df[\"Transaction_ID\"].nunique():,}')
    print(f'   Demographics filled: {with_demographics:,} ({with_demographics/len(df)*100:.1f}%)')
    print(f'   Persona inference: {with_personas:,} ({with_personas/len(df)*100:.1f}%)')
    print(f'   ✅ JOIN multiplication FIXED: Each Transaction_ID is unique')
    print(f'   ✅ Demographics format: Age Gender Role pattern confirmed')

except Exception as e:
    print(f'❌ Smoke test failed: {e}')
    sys.exit(1)
"

      echo "🎉 DEPLOYMENT COMPLETE: All validation gates passed!"
      echo "📊 Results available in out/ directory"
    shell: bash