// Sales Measures
measure "Total Sales" = SUM(mart_tx[NetAmount])
formatString: "₱"#,0

measure "Total Units Sold" = SUM(mart_tx[QuantitySold])
formatString: #,0

measure "Average Transaction Value" =
    DIVIDE([Total Sales], DISTINCTCOUNT(mart_tx[TransactionID]), 0)
formatString: "₱"#,0.00

measure "Total Transactions" = DISTINCTCOUNT(mart_tx[TransactionID])
formatString: #,0

measure "Gross Sales" = SUM(mart_tx[TotalAmount])
formatString: "₱"#,0

measure "Total Discounts" = SUM(mart_tx[DiscountAmount])
formatString: "₱"#,0

measure "Discount Rate" =
    DIVIDE([Total Discounts], [Gross Sales], 0)
formatString: 0.00%

// Profitability Measures
measure "Gross Profit" = SUM(mart_tx[GrossProfit])
formatString: "₱"#,0

measure "Gross Margin %" =
    DIVIDE([Gross Profit], [Total Sales], 0)
formatString: 0.00%

measure "Cost of Goods Sold" = SUM(mart_tx[CostOfGoods])
formatString: "₱"#,0

measure "Average Unit Price" =
    DIVIDE(SUM(mart_tx[TotalAmount]), SUM(mart_tx[QuantitySold]), 0)
formatString: "₱"#,0.00

measure "Average Cost per Unit" =
    DIVIDE(SUM(mart_tx[CostOfGoods]), SUM(mart_tx[QuantitySold]), 0)
formatString: "₱"#,0.00

// Time Intelligence Measures
measure "Sales Last Year" =
    CALCULATE([Total Sales], SAMEPERIODLASTYEAR(dim_date[Date]))
formatString: "₱"#,0

measure "Sales YoY Growth" =
    DIVIDE([Total Sales] - [Sales Last Year], [Sales Last Year], 0)
formatString: 0.00%

measure "Sales YoY Growth ₱" = [Total Sales] - [Sales Last Year]
formatString: "₱"#,0

measure "Sales MTD" =
    CALCULATE([Total Sales], DATESMTD(dim_date[Date]))
formatString: "₱"#,0

measure "Sales QTD" =
    CALCULATE([Total Sales], DATESQTD(dim_date[Date]))
formatString: "₱"#,0

measure "Sales YTD" =
    CALCULATE([Total Sales], DATESYTD(dim_date[Date]))
formatString: "₱"#,0

measure "Sales Previous Month" =
    CALCULATE([Total Sales], PREVIOUSMONTH(dim_date[Date]))
formatString: "₱"#,0

measure "Sales MoM Growth %" =
    DIVIDE([Sales MTD] - [Sales Previous Month], [Sales Previous Month], 0)
formatString: 0.00%

measure "Sales 12 Month Moving Average" =
    AVERAGEX(
        DATESINPERIOD(dim_date[Date], LASTDATE(dim_date[Date]), -12, MONTH),
        [Total Sales]
    )
formatString: "₱"#,0

// Store Performance Measures
measure "Sales per Store" =
    DIVIDE([Total Sales], DISTINCTCOUNT(mart_tx[StoreID]), 0)
formatString: "₱"#,0

measure "Active Stores" =
    CALCULATE(DISTINCTCOUNT(dim_store[StoreID]), dim_store[IsActive] = TRUE)
formatString: #,0

measure "Top Performing Store Sales" =
    MAXX(
        SUMMARIZE(mart_tx, mart_tx[StoreID], "Store Sales", [Total Sales]),
        [Store Sales]
    )
formatString: "₱"#,0

measure "Stores Above Average" =
    SUMX(
        SUMMARIZE(mart_tx, mart_tx[StoreID], "Store Sales", [Total Sales]),
        IF([Store Sales] > [Sales per Store], 1, 0)
    )
formatString: #,0

// Product & Brand Measures
measure "Active Brands" =
    CALCULATE(DISTINCTCOUNT(dim_brand[BrandID]), dim_brand[IsActive] = TRUE)
formatString: #,0

measure "Active Categories" =
    CALCULATE(DISTINCTCOUNT(dim_category[CategoryID]), dim_category[IsActive] = TRUE)
formatString: #,0

measure "Unique Products Sold" = DISTINCTCOUNT(mart_tx[ProductCode])
formatString: #,0

measure "Tobacco Sales" =
    CALCULATE([Total Sales], dim_brand[IsTobacco] = TRUE)
formatString: "₱"#,0

measure "Laundry Sales" =
    CALCULATE([Total Sales], dim_brand[IsLaundry] = TRUE)
formatString: "₱"#,0

measure "Premium Sales" =
    CALCULATE([Total Sales], dim_brand[IsPremium] = TRUE)
formatString: "₱"#,0

measure "Tobacco Sales %" =
    DIVIDE([Tobacco Sales], [Total Sales], 0)
formatString: 0.00%

measure "Premium Sales %" =
    DIVIDE([Premium Sales], [Total Sales], 0)
formatString: 0.00%

// Customer & Transaction Measures
measure "Transactions per Day" =
    DIVIDE([Total Transactions], DISTINCTCOUNT(mart_tx[TransactionDate]), 0)
formatString: #,0.0

measure "Weekend Sales" =
    CALCULATE([Total Sales], mart_tx[IsWeekend] = TRUE)
formatString: "₱"#,0

measure "Weekday Sales" =
    CALCULATE([Total Sales], mart_tx[IsWeekend] = FALSE)
formatString: "₱"#,0

measure "Holiday Sales" =
    CALCULATE([Total Sales], mart_tx[IsHoliday] = TRUE)
formatString: "₱"#,0

measure "Weekend Sales %" =
    DIVIDE([Weekend Sales], [Total Sales], 0)
formatString: 0.00%

measure "Cash Transactions" =
    CALCULATE([Total Transactions], mart_tx[PaymentMethod] = "Cash")
formatString: #,0

measure "Digital Payment %" =
    DIVIDE(
        CALCULATE([Total Transactions], mart_tx[PaymentMethod] <> "Cash"),
        [Total Transactions], 0
    )
formatString: 0.00%

// Regional Performance Measures
measure "NCR Sales" =
    CALCULATE([Total Sales], dim_store[RegionName] = "NCR")
formatString: "₱"#,0

measure "Provincial Sales" =
    CALCULATE([Total Sales], dim_store[RegionName] <> "NCR")
formatString: "₱"#,0

measure "NCR Sales %" =
    DIVIDE([NCR Sales], [Total Sales], 0)
formatString: 0.00%

measure "Top Region Sales" =
    MAXX(
        SUMMARIZE(dim_store, dim_store[RegionName], "Region Sales", [Total Sales]),
        [Region Sales]
    )
formatString: "₱"#,0

// Inventory & Stock Measures
measure "Stock Velocity" =
    DIVIDE([Total Units Sold], DISTINCTCOUNT(mart_tx[ProductCode]), 0)
formatString: #,0.0

measure "Fast Moving Products" =
    SUMX(
        SUMMARIZE(mart_tx, mart_tx[ProductCode], "Product Units", SUM(mart_tx[QuantitySold])),
        IF([Product Units] > [Stock Velocity], 1, 0)
    )
formatString: #,0

// Seasonal & Weather Measures
measure "Hot Weather Sales" =
    CALCULATE([Total Sales], mart_tx[Temperature] > 30)
formatString: "₱"#,0

measure "Rainy Day Sales" =
    CALCULATE([Total Sales], mart_tx[WeatherCondition] = "Rainy")
formatString: "₱"#,0

measure "Seasonal Factor Impact" =
    AVERAGEX(
        FILTER(platinum_predictions, platinum_predictions[SeasonalFactor] <> BLANK()),
        platinum_predictions[SeasonalFactor]
    )
formatString: 0.000

// Prediction & Analytics Measures
measure "Prediction Accuracy" =
    AVERAGE(platinum_predictions[PredictionAccuracy])
formatString: 0.00%

measure "Average Confidence Score" =
    AVERAGE(platinum_predictions[ConfidenceScore])
formatString: 0.00%

measure "Predicted vs Actual Variance" =
    DIVIDE(
        SUM(platinum_predictions[PredictedSales]) - SUM(platinum_predictions[ActualSales]),
        SUM(platinum_predictions[ActualSales]), 0
    )
formatString: 0.00%

measure "High Priority Actions" =
    CALCULATE(
        DISTINCTCOUNT(platinum_predictions[PredictionID]),
        platinum_predictions[ActionPriority] = "High"
    )
formatString: #,0

measure "Market Trend Score" =
    CALCULATE(
        COUNTROWS(platinum_predictions),
        platinum_predictions[MarketTrend] = "Positive"
    )
formatString: #,0

// Performance Ratios
measure "Sales per Square Meter" =
    DIVIDE([Total Sales], DISTINCTCOUNT(dim_store[StoreID]) * 100, 0)
formatString: "₱"#,0

measure "Profit Margin Trend" =
    [Gross Margin %] -
    CALCULATE([Gross Margin %], PREVIOUSMONTH(dim_date[Date]))
formatString: 0.00%

measure "Category Penetration" =
    DIVIDE(DISTINCTCOUNT(mart_tx[CategoryID]), [Active Categories], 0)
formatString: 0.00%

measure "Brand Loyalty Index" =
    DIVIDE(
        SUMX(
            SUMMARIZE(mart_tx, mart_tx[BrandID], "Brand Frequency", COUNT(mart_tx[TransactionID])),
            IF([Brand Frequency] > 1, [Brand Frequency], 0)
        ),
        [Total Transactions], 0
    )
formatString: 0.00%

// Promotional Impact
measure "Promoted Sales" =
    CALCULATE([Total Sales], NOT(ISBLANK(mart_tx[PromotionID])))
formatString: "₱"#,0

measure "Promotion Effectiveness %" =
    DIVIDE([Promoted Sales], [Total Sales], 0)
formatString: 0.00%

measure "Promotional Lift" =
    AVERAGEX(
        FILTER(platinum_predictions, platinum_predictions[PromotionalImpact] <> BLANK()),
        platinum_predictions[PromotionalImpact]
    )
formatString: 0.00%

// Risk & Opportunity Measures
measure "Demand Volatility Score" =
    AVERAGE(platinum_predictions[DemandVolatility])
formatString: 0.00%

measure "Supply Chain Risk Level" =
    CALCULATE(
        COUNTROWS(platinum_predictions),
        platinum_predictions[SupplyChainRisk] = "High"
    )
formatString: #,0

measure "Price Elasticity Average" =
    AVERAGE(platinum_predictions[PriceElasticity])
formatString: 0.000

measure "Cross Category Impact" =
    AVERAGE(platinum_predictions[CrossCategoryEffect])
formatString: 0.00%

// Ranking Measures
measure "Store Sales Rank" =
    RANKX(
        ALL(dim_store[StoreName]),
        [Total Sales],
        ,
        DESC
    )
formatString: #,0

measure "Brand Sales Rank" =
    RANKX(
        ALL(dim_brand[BrandName]),
        [Total Sales],
        ,
        DESC
    )
formatString: #,0

measure "Category Sales Rank" =
    RANKX(
        ALL(dim_category[CategoryL1]),
        [Total Sales],
        ,
        DESC
    )
formatString: #,0

// ========================================
// CONVERSATION AI & SENTIMENT MEASURES
// ========================================

// Basic Conversation Metrics
measure "Total Conversations" = DISTINCTCOUNT(silver_conversation_ai[canonical_tx_id])
formatString: #,0

measure "Processed Conversations" =
    CALCULATE(
        [Total Conversations],
        silver_conversation_ai[processing_status] = "completed"
    )
formatString: #,0

measure "Conversation Processing Rate" =
    DIVIDE([Processed Conversations], [Total Conversations], 0)
formatString: 0.00%

measure "Average Text Length" =
    AVERAGE(silver_conversation_ai[text_length])
formatString: #,0

measure "Average Word Count" =
    AVERAGE(silver_conversation_ai[word_count])
formatString: #,0

measure "Average Key Phrases" =
    AVERAGE(silver_conversation_ai[key_phrases_count])
formatString: #,0.0

// Sentiment Analysis Measures
measure "Average Sentiment Score" =
    AVERAGE(silver_conversation_ai[sentiment_score])
formatString: 0.000

measure "Positive Conversations" =
    CALCULATE([Total Conversations], silver_conversation_ai[sentiment] = "positive")
formatString: #,0

measure "Negative Conversations" =
    CALCULATE([Total Conversations], silver_conversation_ai[sentiment] = "negative")
formatString: #,0

measure "Neutral Conversations" =
    CALCULATE([Total Conversations], silver_conversation_ai[sentiment] = "neutral")
formatString: #,0

measure "Positive Sentiment %" =
    DIVIDE([Positive Conversations], [Total Conversations], 0)
formatString: 0.00%

measure "Negative Sentiment %" =
    DIVIDE([Negative Conversations], [Total Conversations], 0)
formatString: 0.00%

measure "Neutral Sentiment %" =
    DIVIDE([Neutral Conversations], [Total Conversations], 0)
formatString: 0.00%

measure "Net Sentiment Score" =
    [Positive Sentiment %] - [Negative Sentiment %]
formatString: 0.00%

measure "Average Positive Confidence" =
    AVERAGE(silver_conversation_ai[sentiment_pos])
formatString: 0.000

measure "Average Negative Confidence" =
    AVERAGE(silver_conversation_ai[sentiment_neg])
formatString: 0.000

// Language Distribution Measures
measure "English Conversations" =
    CALCULATE([Total Conversations], silver_conversation_ai[language] = "en")
formatString: #,0

measure "Tagalog Conversations" =
    CALCULATE([Total Conversations], silver_conversation_ai[language] = "tl")
formatString: #,0

measure "Cebuano Conversations" =
    CALCULATE([Total Conversations], silver_conversation_ai[language] = "ceb")
formatString: #,0

measure "English Conversations %" =
    DIVIDE([English Conversations], [Total Conversations], 0)
formatString: 0.00%

measure "Local Language %" =
    DIVIDE([Tagalog Conversations] + [Cebuano Conversations], [Total Conversations], 0)
formatString: 0.00%

measure "Average Language Confidence" =
    AVERAGE(silver_conversation_ai[language_confidence])
formatString: 0.000

// Sentiment-Revenue Correlation
measure "Positive Sentiment Revenue" =
    CALCULATE([Total Sales], silver_conversation_ai[sentiment] = "positive")
formatString: "₱"#,0

measure "Negative Sentiment Revenue" =
    CALCULATE([Total Sales], silver_conversation_ai[sentiment] = "negative")
formatString: "₱"#,0

measure "Average Revenue per Positive Conversation" =
    DIVIDE([Positive Sentiment Revenue], [Positive Conversations], 0)
formatString: "₱"#,0.00

measure "Average Revenue per Negative Conversation" =
    DIVIDE([Negative Sentiment Revenue], [Negative Conversations], 0)
formatString: "₱"#,0.00

measure "Sentiment Revenue Impact" =
    [Average Revenue per Positive Conversation] - [Average Revenue per Negative Conversation]
formatString: "₱"#,0.00

// ========================================
// ADVANCED AI ANALYTICS (PLATINUM LAYER)
// ========================================

measure "ML Processed Conversations" = DISTINCTCOUNT(platinum_conversation_ai[canonical_tx_id])
formatString: #,0

measure "Average Sentiment Confidence (ML)" =
    AVERAGE(platinum_conversation_ai[sentiment_confidence])
formatString: 0.000

measure "High Engagement Conversations" =
    CALCULATE([ML Processed Conversations], platinum_conversation_ai[engagement_level] = "High")
formatString: #,0

measure "High Engagement Rate" =
    DIVIDE([High Engagement Conversations], [ML Processed Conversations], 0)
formatString: 0.00%

measure "Complaint Conversations" =
    CALCULATE([ML Processed Conversations], platinum_conversation_ai[is_complaint] = TRUE)
formatString: #,0

measure "Praise Conversations" =
    CALCULATE([ML Processed Conversations], platinum_conversation_ai[is_praise] = TRUE)
formatString: #,0

measure "Complaint Rate" =
    DIVIDE([Complaint Conversations], [ML Processed Conversations], 0)
formatString: 0.00%

measure "Praise Rate" =
    DIVIDE([Praise Conversations], [ML Processed Conversations], 0)
formatString: 0.00%

// Topic Analysis Measures
measure "Average Topic Probability" =
    AVERAGE(platinum_conversation_ai[topic_probability])
formatString: 0.000

measure "High Confidence Topics" =
    CALCULATE([ML Processed Conversations], platinum_conversation_ai[topic_confidence_level] = "High")
formatString: #,0

measure "High Topic Confidence Rate" =
    DIVIDE([High Confidence Topics], [ML Processed Conversations], 0)
formatString: 0.00%

measure "Business Keywords Found" =
    CALCULATE([ML Processed Conversations], platinum_conversation_ai[has_business_keywords] = TRUE)
formatString: #,0

measure "Emotion Keywords Found" =
    CALCULATE([ML Processed Conversations], platinum_conversation_ai[has_emotion_keywords] = TRUE)
formatString: #,0

measure "Product Keywords Found" =
    CALCULATE([ML Processed Conversations], platinum_conversation_ai[has_product_keywords] = TRUE)
formatString: #,0

measure "Business Keywords Rate" =
    DIVIDE([Business Keywords Found], [ML Processed Conversations], 0)
formatString: 0.00%

// Conversation Classification Measures
measure "Detailed Conversations" =
    CALCULATE([ML Processed Conversations], platinum_conversation_ai[length_classification] = "Detailed")
formatString: #,0

measure "Standard Conversations" =
    CALCULATE([ML Processed Conversations], platinum_conversation_ai[length_classification] = "Standard")
formatString: #,0

measure "Brief Conversations" =
    CALCULATE([ML Processed Conversations], platinum_conversation_ai[length_classification] = "Brief")
formatString: #,0

measure "Detailed Conversation Rate" =
    DIVIDE([Detailed Conversations], [ML Processed Conversations], 0)
formatString: 0.00%

// Conversation Quality Indicators
measure "Strong Sentiment Conversations" =
    CALCULATE([ML Processed Conversations], platinum_conversation_ai[sentiment_intensity] = "Strong")
formatString: #,0

measure "Strong Sentiment Rate" =
    DIVIDE([Strong Sentiment Conversations], [ML Processed Conversations], 0)
formatString: 0.00%

measure "Average Phrase Length (ML)" =
    AVERAGE(platinum_conversation_ai[avg_phrase_length])
formatString: #,0.0

// Time-based AI Measures
measure "Conversations Last Month" =
    CALCULATE(
        [Total Conversations],
        DATESINPERIOD(
            dim_date[Date],
            LASTDATE(dim_date[Date]),
            -1,
            MONTH
        )
    )
formatString: #,0

measure "Sentiment Trend (MoM)" =
    [Average Sentiment Score] -
    CALCULATE(
        [Average Sentiment Score],
        DATESINPERIOD(
            dim_date[Date],
            LASTDATE(dim_date[Date]),
            -1,
            MONTH
        )
    )
formatString: 0.000

measure "Conversation Growth Rate" =
    DIVIDE(
        [Total Conversations] - [Conversations Last Month],
        [Conversations Last Month],
        0
    )
formatString: 0.00%

// AI Data Quality Measures
measure "Processing Success Rate" =
    DIVIDE(
        CALCULATE([Total Conversations], silver_conversation_ai[processing_status] = "completed"),
        [Total Conversations],
        0
    )
formatString: 0.00%

measure "Failed Processing Count" =
    CALCULATE([Total Conversations], silver_conversation_ai[processing_status] = "failed")
formatString: #,0

measure "Average Processing Quality Score" =
    ([Average Language Confidence] + [Average Sentiment Confidence (ML)]) / 2
formatString: 0.000