name: auto-sync-ci

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
  workflow_dispatch:

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}/auto-sync

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: |
          docker build \
            -f etl/agents/Dockerfile \
            -t $IMAGE_NAME:sha-${GITHUB_SHA::7} \
            .

      - name: Push SHA tag
        run: docker push $IMAGE_NAME:sha-${GITHUB_SHA::7}

      - name: Push channel tags (main -> latest)
        if: github.ref == 'refs/heads/main'
        run: |
          docker tag $IMAGE_NAME:sha-${GITHUB_SHA::7} $IMAGE_NAME:latest
          docker push $IMAGE_NAME:latest

      - name: Push semver tag
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          VER=${GITHUB_REF#refs/tags/}
          docker tag $IMAGE_NAME:sha-${GITHUB_SHA::7} $IMAGE_NAME:${VER}
          docker push $IMAGE_NAME:${VER}